/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5r7Egm6VDeY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BirdIcon className="h-6 w-6" />
          <span className="sr-only">Pakaak</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Features
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Testimonials
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Download
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 sm:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Fresh Chicken Delivered to Your Doorstep
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Pakaak is the ultimate app for on-demand, high-quality chicken delivery. Get your favorite cuts
                    delivered in no time.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Download App
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <img
                src="https://t3.ftcdn.net/jpg/05/13/37/62/360_F_513376282_X45C2UKOQGXJyoZK2JEplrNef8Ov9dAv.jpg"
               
                alt="Hero"
                className="mx-auto aspect-video object-cover overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Key Features</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Why Choose Pakaak?</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Pakaak offers a seamless and convenient way to get fresh chicken delivered to your doorstep. Discover
                  the key features that make us the best choice for your chicken needs.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">On-Demand Delivery</h3>
                      <p className="text-muted-foreground">
                        Get your chicken delivered in as little as 30 minutes. No more waiting for days or dealing with
                        unreliable schedules.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">High-Quality Chicken</h3>
                      <p className="text-muted-foreground">
                        Our chicken is sourced from the best local farms, ensuring freshness and quality in every bite.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Easy Ordering</h3>
                      <p className="text-muted-foreground">
                        With our user-friendly app, you can browse, select, and order your favorite chicken cuts in just
                        a few taps.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <img
                src="https://media.istockphoto.com/id/627272886/photo/chicken-legs.jpg?s=612x612&w=0&k=20&c=rPrFEnVCPw9aayUMcgP5Z3NI6u6op1mHlyhHFb8W3TI="
                alt="Image"
                className="mx-auto aspect-video object-cover overflow-hidden rounded-xl  object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Testimonials</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">What Our Customers Say</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Hear from our satisfied customers and learn why they love Pakaak for their chicken delivery needs.
                </p>
              </div>
              <div className="divide-y rounded-lg border">
                <div className="grid w-full grid-cols-1 items-stretch justify-center divide-x md:grid-cols-2 lg:grid-cols-3">
                  <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                    <div className="grid gap-2">
                      <div className="flex items-center gap-2">
                        <div className="rounded-full bg-primary px-3 py-1 text-primary-foreground">5.0</div>
                        <div className="flex items-center gap-1 text-yellow-500">
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        "Pakaak has been a game-changer for my family. The\n on-demand delivery and high-quality chicken
                        have made\n our lives so much easier."
                      </p>
                      <div className="text-sm font-medium">- Mehboob, Pakaak Customer</div>
                    </div>
                  </div>
                  <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                    <div className="grid gap-2">
                      <div className="flex items-center gap-2">
                        <div className="rounded-full bg-primary px-3 py-1 text-primary-foreground">4.8</div>
                        <div className="flex items-center gap-1 text-yellow-500">
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        "I've been using Pakaak for months and the service has\n been consistently excellent. The
                        chicken is always\n fresh and the delivery is lightning-fast."
                      </p>
                      <div className="text-sm font-medium">- Vikas, Pakaak Customer</div>
                    </div>
                  </div>
                  <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
                    <div className="grid gap-2">
                      <div className="flex items-center gap-2">
                        <div className="rounded-full bg-primary px-3 py-1 text-primary-foreground">4.9</div>
                        <div className="flex items-center gap-1 text-yellow-500">
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                          <StarIcon className="h-4 w-4" />
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        "Pakaak has become an essential part of my weekly\n routine. The convenience and quality are
                        unbeatable.\n Highly recommended!"
                      </p>
                      <div className="text-sm font-medium">- Aditya, Pakaak Customer</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Download</div>
                <h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Get Pakaak on Your Devices
                </h2>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Download on Android
                  </Link>
                </div>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Availability</div>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
                  Pakaak is available for download on Google Play Store. Get the app now and enjoy the
                  convenience of on-demand chicken delivery.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Pakaak. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function BirdIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 7h.01" />
      <path d="M3.4 18H12a8 8 0 0 0 8-8V7a4 4 0 0 0-7.28-2.3L2 20" />
      <path d="m20 7 2 .5-2 .5" />
      <path d="M10 18v3" />
      <path d="M14 17.75V21" />
      <path d="M7 18a6 6 0 0 0 3.84-10.61" />
    </svg>
  )
}


function StarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function XIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
